### ISSUE TITLE
Feature request: Support Ruby 1.8

### ISSUE THREAD

**Issue by eric** [ryanlecompte/redis_failover#7] opened 2012-04-21 15:10 UTC
I'm still using Ruby 1.8, so I would love to see support for it.

I can't think of anything that would prevent it from working, so I'll definitely be trying to make it work.

**Comment by ryanlecompte** [comment] 2012-04-22 09:56
The main reason for not supporting 1.8 is that it's basically EOL'd and I'd really like to be able to freely use Ruby 1.9 features. However, I don't think I've used 1.9 specific features so far in redis_failover, although I'm not entirely sure. I started programming in Ruby when 1.9 was already released, so I never had direct experience with ensuring that my code worked on the older 1.8.7 release.

Do you have any upcoming plans to switch to 1.9?

**Comment by eric** [comment] 2012-04-22 10:03
I don't have any plans to move my entire codebase over. I do expect I'll move some components, but I believe it'll be a while before I don't have anything using 1.8.

Once you have stuff in production, it becomes a pretty big pain in the ass to make that sort of change.

**Comment by ryanlecompte** [comment] 2012-04-22 10:11
I see. I'd love for you to give redis_failover a shot with 1.8 and let me know how it goes, then.

**Comment by joshuakfarrar** [comment] 2012-06-13 01:17
Ruby 1.8 on Ubuntu.

``` shell
/usr/lib/ruby/vendor_ruby/1.8/rubygems/specification.rb:1625:in `raise_if_conflicts': Unable to activate redis-namespace-1.2.0, because redis-2.2.0 conflicts with redis (~> 3.0.0) (Gem::LoadError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/specification.rb:740:in `activate'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/specification.rb:774:in `activate_dependencies'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/specification.rb:760:in `each'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/specification.rb:760:in `activate_dependencies'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/specification.rb:744:in `activate'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:1209:in `gem'
    from /usr/local/bin/redis_node_manager:18
```

**Comment by ryanlecompte** [comment] 2012-06-13 01:20
redis_failover does not work with ruby 1.8.

**Comment by eric** [comment] 2012-06-13 01:21
Can we make it work?

**Comment by joshuakfarrar** [comment] 2012-06-13 01:51
``` shell
vagrant@redis3:~$ ruby -v
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
vagrant@redis3:~$ sudo redis_node_manager 
/usr/lib/ruby/1.9.1/rubygems/specification.rb:1615:in `raise_if_conflicts': Unable to activate redis-namespace-1.2.0, because redis-2.2.0 conflicts with redis (~> 3.0.0) (Gem::LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:738:in `activate'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:764:in `block in activate_dependencies'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:758:in `each'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:758:in `activate_dependencies'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:742:in `activate'
    from /usr/lib/ruby/1.9.1/rubygems.rb:1211:in `gem'
    from /usr/local/bin/redis_node_manager:18:in `<main>'
```

It apparently doesn't like 1.9.3 either (Ubuntu 12.04) .. Is there something I'm doing wrong here? I'm not a Ruby pro.

**Comment by joshuakfarrar** [comment] 2012-06-13 01:55
``` shell
vagrant@redis3:~$ gem list --local

*** LOCAL GEMS ***

backports (2.5.3)
little-plugger (1.1.3)
logging (1.7.2)
multi_json (1.3.6)
redis (3.0.1, 2.2.0)
redis-namespace (1.2.0)
redis_failover (0.8.4)
zk (1.6.3)
zookeeper (1.2.9)
```

**Comment by ryanlecompte** [comment] 2012-06-13 02:19
It looks like it's picking up Redis version 3.0. Could you try starting the node manager with bundle exec?

**Comment by joshuakfarrar** [comment] 2012-06-14 15:10
Very vague error after I got the rake, yard, and rspec gems installed

``` shell
vagrant@nm0:~/redis_failover$ bundle exec redis_failover
Bundler could not find compatible versions for gem "redis":
  In Gemfile:
    redis_failover depends on
      redis (~> 3.0.0)

    redis_failover depends on
      redis (2.2.0)


vagrant@nm0:~/redis_failover$ sudo gem list --local

*** LOCAL GEMS ***

backports (2.5.3)
diff-lcs (1.1.3)
little-plugger (1.1.3)
logging (1.7.2)
multi_json (1.3.6)
rake (0.9.2.2)
redis (3.0.1, 2.2.0)
redis-namespace (1.2.0)
redis_failover (0.8.4)
rspec (2.10.0)
rspec-core (2.10.1)
rspec-expectations (2.10.0)
rspec-mocks (2.10.1)
yard (0.8.2.1)
zk (1.6.3)
zookeeper (1.2.9)
vagrant@nm0:~/redis_failover$ ls
bin  Changes.md  examples  Gemfile  lib  LICENSE  Rakefile  README.md  redis_failover.gemspec  spec
```

**Comment by joshuakfarrar** [comment] 2012-06-14 15:21
Oh wait, removed the requirement redis-namespace from redis_failover.gemspec, and got the usage message instead of an immediate exception regarding deps -- lemme give it a go on my ZK / redis cluster and I'll post back.

``` shell
vagrant@nm0:~/redis_failover/bin$ bundle exec redis_node_manager 
Usage: redis_node_manager [OPTIONS]

Specific options:
    -n, --nodes NODES                Comma-separated redis host:port pairs
    -z, --zkservers SERVERS          Comma-separated ZooKeeper host:port pairs
    -p, --password PASSWORD          Redis password
        --znode-path PATH            Znode path override for storing redis server list
        --max-failures COUNT         Max failures before manager marks node unavailable
    -C, --config PATH                Path to YAML config file
    -E, --environment ENV            Config environment to use
    -h, --help                       Display all options
```

**Comment by joshuakfarrar** [comment] 2012-06-14 16:27
Alright, that seemed to work.

``` shell
vagrant@nm0:~/redis_failover/bin$ bundle exec redis_node_manager -n 192.168.0.3,192.168.0.4,192.168.0.5 -z 192.168.0.3:2181,192.168.0.4:2181,192.168.0.5:2181
2012-06-14 16:23:01 UTC RedisFailover 20955 INFO: Redis Node Manager v0.8.4 starting (ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux])
2012-06-14 16:23:01 UTC RedisFailover 20955 INFO: Waiting to become master Node Manager ...
2012-06-14 16:23:01 UTC RedisFailover 20955 INFO: Acquired master Node Manager lock
2012-06-14 16:23:01 UTC RedisFailover 20955 INFO: Managing master (192.168.0.3:6379) and slaves (192.168.0.4:6379, 192.168.0.5:6379)
2012-06-14 16:23:01 UTC RedisFailover 20955 INFO: 192.168.0.4:6379 is now a slave of 192.168.0.3:6379
2012-06-14 16:23:02 UTC RedisFailover 20955 INFO: 192.168.0.5:6379 is now a slave of 192.168.0.3:6379
2012-06-14 16:23:02 UTC RedisFailover 20955 INFO: Created ZooKeeper node /redis_failover_nodes
```

Then I manually killed redis-server on 192.168.0.3..

``` shell
vagrant@redis0:~$ ps -e | grep redis-server
 3145 ?        00:00:02 redis-server
vagrant@redis0:~$ sudo kill -9 3145
vagrant@redis0:~$ ps -e | grep redis-server
```

And automatic failover happened :)

``` shell
2012-06-14 16:24:55 UTC RedisFailover 20955 INFO: Handling unavailable node: 192.168.0.3:6379
2012-06-14 16:24:55 UTC RedisFailover 20955 INFO: Demoting currently unavailable master 192.168.0.3:6379.
2012-06-14 16:24:55 UTC RedisFailover 20955 INFO: Deleted ZooKeeper node /redis_failover_nodes
2012-06-14 16:24:55 UTC RedisFailover 20955 INFO: 192.168.0.4:6379 is now a slave of 192.168.0.5:6379
2012-06-14 16:24:55 UTC RedisFailover 20955 INFO: 192.168.0.5:6379 is now master
2012-06-14 16:24:55 UTC RedisFailover 20955 INFO: Created ZooKeeper node /redis_failover_nodes
2012-06-14 16:24:55 UTC RedisFailover 20955 INFO: Successfully promoted 192.168.0.5:6379 to master.
```

``` shell
redis 192.168.0.4:6379> info
redis_version:2.2.12
...
role:slave
master_host:192.168.0.5
master_port:6379
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0
...
```

So the solution to my problem was getting rid of the redis-namespace dependency from the gemspec file because redis-namespace links to redis v 3.0.1, which is incompatible with v 2.2.0

**Comment by ryanlecompte** [comment] 2012-06-14 16:36
That's great! It looks like I just need to be more specific with redis-namespace version range in the redis_failover.gemspec so that it doesn't link to v3.0.1. I'll do that now. Thanks. Are you planning on rolling this out at your company if all goes well or just playing for now?

**Comment by joshuakfarrar** [comment] 2012-06-14 16:45
I'm playing with this for potential deployment :) I started working on my own version (quite similar, really) in Node, but saw this project and decided to see if I could get it running and if it met our needs (and, so far, it does, though we still need to run tests in dev (obviously))

**Comment by ryanlecompte** [comment] 2012-06-14 16:49
Awesome. I just pushed up a fix for the gemspec issue in master. Let me
know if I can assist any further. :)

On Thu, Jun 14, 2012 at 9:45 AM, Joshua Farrar <
reply@reply.github.com

**Comment by joshuakfarrar** [comment] 2012-06-14 17:54
Wicked, thanks dude!

**Comment by ryanlecompte** [comment] 2012-06-14 23:13
Actually @Zipp, if you're a savvy node.js developer, I'd _love_ to have a node.js client that talks to the redis_failover backend. I'm not sure of the state of the ZooKeeper libraries for node.js, but I don't think it would be too hard to do. Right now it's a ruby-specific solution, but having a node.js/python/whatever client library would be awesome.

**Comment by ghost** [comment] 2012-06-27 23:56
Would it be possible to push this change out to rubygems.org in order to easily install this gem on our clusters? We are also somewhat stuck on Ruby 1.8.x at the moment

**Comment by joshuakfarrar** [comment] 2012-06-28 02:17
I don't believe redis_failover actually supports 1.8.0; my bug was a separate issue that I was blaming on 1.8.x not being supported.

**Comment by ryanlecompte** [comment] 2012-06-28 04:28
That's correct. Right now 1.8.7 is unsupported. I'd be curious to know what breaks though, as I've never actually tried to use it on 1.8.7.

**Comment by ghost** [comment] 2012-06-28 16:56
Well, I've tried getting this running with 1.8.7, I can bundle without problems, but rake fails with the following output (paste bin link) http://pastebin.com/TaKSER59

Could this be outdated tests or a legitimate issue with 1.8.7?

**Comment by ryanlecompte** [comment] 2012-06-28 16:57
The tests definitely don't fail on 1.9.3. What if you use bundle exec rake?

On Thu, Jun 28, 2012 at 9:56 AM, influenza <
reply@reply.github.com

**Comment by ghost** [comment] 2012-06-28 17:00
Executing 'bundle exec rake' from the repo root causes the same test failures :/ Is there some way I could help you isolate this and see if it's maybe a quick fix?

**Comment by ryanlecompte** [comment] 2012-06-28 17:03
It could be an issue with just the tests. Would be great if you could try to actually use the client and server and report back what you see.

**Comment by ghost** [comment] 2012-06-28 17:07
Will do. Hopefully I'll have some info for you in the next couple of hours. Thanks for your responsiveness

**Comment by ghost** [comment] 2012-06-28 20:30
@ryanlecompte Seems to work fine under 1.8.7 - so if you could push up that updated gemspec to rubygems.org, I think I'll be able to cleanly install redis_failover via ruby gems :)

**Comment by ryanlecompte** [comment] 2012-06-28 20:34
Wow, that's good to know! I'll try to push up a new version later this
afternoon. Thanks for testing. This should be good news for @eric. :)

On Thu, Jun 28, 2012 at 1:30 PM, influenza <
reply@reply.github.com

**Comment by ghost** [comment] 2012-06-28 21:11
No problem. Thanks for making this tool freely available! That's a good deal less HA boilerplate I need to worry about

**Comment by joshuakfarrar** [comment] 2012-06-28 21:22
If this works in 1.8, the issue can be closed?

**Comment by ryanlecompte** [comment] 2012-06-29 17:36
Okay, 0.8.6 was just pushed. Thanks!

**Comment by ryanlecompte** [comment] 2012-06-29 17:36
Closing.

**Closed as completed by ryanlecompte** 2012-06-29 17:36 UTC
